apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: xsalgovic-patient-fe
spec:
  module-uri:
    http://xsalgovic-patient-fe.wac-hospital/build/patient-fe.esm.js
    # module web komponentu pre tento mikroFE
    # - umiestnený v namespace wac-hospital
  navigation:
    - element: xsalgovic-patient-card # element, ktorý bude vložený na stránku
      # pri navigácii na zoznam čakajúcich
      path: xsalgovic-patient-card # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Karta pacienta # názov mikro aplikácie
      details: Zobrazí detail karty pacienta - xsalgovic
      attributes:
        - name: api-base
          value: http://localhost:30081/api
  preload: false # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy:
    true # pre komponenty v rámci klastra, neprístupné na verejnej sieti
    # musí byť táto hodnota nastavená na true
  hash-suffix:
    v1alpha1 # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
    # sa mení názov URL pre modul a tým je možné predísť problémom
    # s verziami vo vyrovnávacích pamätiach
